# -*- coding: utf-8 -*-
"""
Created on Wed Jul  4 13:14:28 2018

@author: Ron
"""

testGroupDict = dict()
# Create CBC Map:
testGroupDict['HCT'] = 'Hematocrit'
testGroupDict['HGB'] = 'Hemoglobin'
testGroupDict['MCH'] = 'MCH'
testGroupDict['MCHC'] = 'MCHC-M'
testGroupDict['MCV'] = 'MCV'
testGroupDict['MPV'] = 'MPV'
testGroupDict['PLATELETS'] = 'Platelets'
testGroupDict['RBC'] = 'RBC'
testGroupDict['RDW'] = 'RDW'
testGroupDict['WBC'] = 'WBC'
testGroupDict['BASOPHILS %'] = 'Basophils%' 
testGroupDict['EOSINOPHILS %'] = 'Eosinophils%' 
testGroupDict['LYMPHOCYTES %'] = 'Lymphocytes%'
testGroupDict['NEUTROPHILS %'] = 'Neutrophils%'
testGroupDict['MONOCYTES %'] = 'Monocytes%'
testGroupDict['RBC NUCLEATED'] = 'nRBC'
testGroupDict['BANDS %'] = 'Bands%' 
testGroupDict['NEUTROPHILS'] = 'Neutrophils#'
testGroupDict['BASOPHILS'] = 'Basophils#'
testGroupDict['EOSINOPHILS'] = 'Eosinophils#'
testGroupDict['LYMPHOCYTES'] = 'Lymphocytes#'
testGroupDict['MONOCYTES'] = 'Monocytes#'

##################################################################################################
# Lab Mapping exists in THIN
##################################################################################################

testGroupDict['CHLORIDE'] = 'Cl'
testGroupDict['CO2'] = 'CO2'
testGroupDict['POTASSIUM'] = 'K+'
testGroupDict['SODIUM'] = 'Na'
testGroupDict['BUN'] = 'Urea'
testGroupDict['CREATININE'] = 'Creatinine'
testGroupDict['CHOLESTEROL'] = 'Cholesterol'
testGroupDict['HDL'] = 'HDL'
testGroupDict['LDL CALCULATED'] = 'LDL'
testGroupDict['TRIGLYCERIDE'] = 'Triglycerides'
testGroupDict['ALT'] = 'ALT'
testGroupDict['LDL'] = 'LDL'
testGroupDict['CALCIUM'] = 'Ca'
testGroupDict['FERRITIN'] = 'Ferritin'
testGroupDict['GLUCOSE, RANDOM'] = 'RandomGlucose'
testGroupDict['BILIRUBIN, TOTAL'] = 'Bilirubin'
testGroupDict['CK'] = 'CK'
testGroupDict['ALKALINE PHOSPHATASE'] = 'ALKP'
testGroupDict['PHOSPHORUS'] = 'Phosphore'
testGroupDict['ALBUMIN'] = 'Albumin'
testGroupDict['GLOBULIN'] = 'Globulin'
testGroupDict['TOTAL PROTEIN'] = 'Protein_Total'
testGroupDict['AST'] = 'AST'
testGroupDict['INR'] = 'INR'
testGroupDict['PT INR'] = 'INR'
testGroupDict['PT-INR'] = 'INR'
testGroupDict['AMYLASE'] = 'Amylase'
testGroupDict['BILIRUBIN, DIRECT'] = 'DirectBilirubin'
testGroupDict['URIC ACID'] = 'Uric_Acid'
testGroupDict['25-HYDROXYVITAMIN D'] = 'VitaminD_25'
testGroupDict['VITAMIN D, 25-HYDROXY, D2'] = 'VitaminD_25'
testGroupDict['VITAMIN D, 25-HYDROXY, D3'] = 'VitaminD_25'
testGroupDict['VIT B12'] = 'B12'
testGroupDict['FOLATE'] = 'Follic_Acid'
testGroupDict['TRIGLYCERIDE, NONFASTING'] = 'Triglycerides'
testGroupDict['GGT'] = 'GGT'
testGroupDict['LDH'] = 'LDH'
testGroupDict['PT'] = 'PT'
testGroupDict['Vitamin D, 25-OH, D2'] = 'VitaminD_25'
testGroupDict['Vitamin D, 25-OH, D3'] = 'VitaminD_25'
testGroupDict['Vitamin D, 25-OH, Total'] = 'VitaminD_25'
testGroupDict['IRON'] = 'Iron_Fe'
testGroupDict['TRANSFERRIN'] = 'Transferrin'
#['SERUM SPECIMEN'] # Remove - 1 value
#['APTT IMMEDIATELY AFTER ADDITION OF NORMAL PLASMA']  Remove - 1 value
testGroupDict['CHOLESTEROL, NON-HDL'] = 'NonHDLCholesterol'
testGroupDict['INR, BLOOD, POCT'] = 'INR'
testGroupDict['GLUCOSE, BLOOD, POCT'] = 'Glucose'
testGroupDict['HGB A1C, EXTERNAL RESULT.'] = 'HbA1C' 
testGroupDict['GLUCOSE, BLOOD'] = 'Glucose'
testGroupDict['CALCIUM, PRE DIALYSIS'] = 'Ca'
testGroupDict['PHOSPHORUS, PRE DIALYSIS'] = 'Phosphore'
testGroupDict['CREATININE PRE DIALYSIS,SER/PLAS'] = 'Creatinine'
testGroupDict['BUN, PRE DIALYSIS'] = 'Urea'
testGroupDict['GLUCOSE POST FAST'] = 'Glucose'
testGroupDict['INR, EXTERNAL REPORT'] = 'INR'
testGroupDict['INR, PATIENT PERFORMED'] = 'INR'
testGroupDict['APTT'] = 'PTT'
testGroupDict['APTT IMMEDIATELY AFTER ADDITION OF NORMAL PLASMA'] = 'PTT'
testGroupDict['TOTAL IRON BINDING CAPACITY, UNSATURATED'] = 'TIBC'
testGroupDict['TOTAL IRON BINDING CAPACITY'] = 'TIBC'
testGroupDict['TOTAL IRON BINDING CAPACITY, UNSATURATED'] = 'TIBC'
testGroupDict['GLOMERULAR FILTRATION RATE'] = 'GFR'
testGroupDict['GLUCOSE, FASTING'] = 'Glucose'
testGroupDict['HGBA1C%'] = 'HbA1C'
testGroupDict['ALBUMIN DIALYSIS, BROMCRESOL GREEN'] = 'Albumin'
testGroupDict['component2'] = 'Repo'
testGroupDict['GFR EST'] = 'eGFR'
testGroupDict['SGPT (ALT)'] = 'ALT'
testGroupDict['CALCULATED LDL'] = 'LDL'
testGroupDict['CHOL/HDL RATIO'] = 'Cholesterol_over_HDL'
testGroupDict['DIRECT HDL'] = 'HDL'
testGroupDict['TRIGLYCERIDES'] = 'Triglycerides'
testGroupDict['GLUC-FAST'] = 'Glucose'
testGroupDict['TOTAL CALCIUM'] = 'Ca'
testGroupDict['HEMOGLOBIN A1C'] = 'HbA1C'
testGroupDict['SGOT (AST)'] = 'AST'
testGroupDict['VITAMIN B12'] = 'B12'
testGroupDict['TIBC'] = 'TIBC'
testGroupDict['GLUC-RAND'] = 'RandomGlucose'
testGroupDict['CHOL/HDL RATIO'] = 'Cholesterol_over_HDL'
testGroupDict['ALK PHOS'] = 'ALKP'
testGroupDict['CK-TOTAL'] = 'CK'
testGroupDict['FASTING GLUCOSE'] = 'Glucose'
testGroupDict['ALK PHOS'] = 'ALKP'
testGroupDict['TOTAL BILIRUBIN'] = 'Bilirubin'
testGroupDict['DIRECT LDL'] = 'LDL'
testGroupDict['VITAMIN B12'] = 'B12'
testGroupDict['GAMMA GT'] = 'GGT'
testGroupDict['CO2 TOTAL'] = 'CO2'
testGroupDict['DIRECT LDL'] = 'LDL'
testGroupDict['BILI TOTAL'] = 'Bilirubin'
testGroupDict['SGPT (ALT)'] = 'ALT'
testGroupDict['DIRECT HDL'] = 'HDL'
testGroupDict['BILI 1 MIN DIRECT'] = 'DirectBilirubin'
testGroupDict['TIBC'] = 'TIBC'
testGroupDict['Total Amylase'] = 'Amylase'
testGroupDict['BILI DIRECT'] = 'DirectBilirubin'
testGroupDict['FOLATE (FOLIC ACID)'] = 'Follic_Acid'
testGroupDict['BLOOD AMYLASE'] = 'Amylase'
testGroupDict['TRIGLYCERIDES'] = 'Triglycerides'
testGroupDict['VITAMIN B12'] = 'B12'
testGroupDict['BILI TOTAL'] = 'Bilirubin'
testGroupDict['HEMOGLOBIN A1C'] = 'HbA1C'
testGroupDict['GLUCOSE'] = 'RandomGlucose'
testGroupDict['SERUM CALCIUM'] = 'Ca'
testGroupDict['FBS'] = 'Glucose'
testGroupDict['ALK PHOS'] = 'ALKP'
testGroupDict['TOTAL BILIRUBIN'] = 'Bilirubin'
testGroupDict['TIBC'] = 'TIBC'
testGroupDict['CALCULATED LDL'] = 'LDL'
testGroupDict['CHOL/HDL RATIO'] = 'Cholesterol_over_HDL'
testGroupDict['DIRECT HDL'] = 'HDL'
testGroupDict['TRIGLYCERIDES'] = 'Triglycerides'
testGroupDict['DIRECT HDL'] = 'HDL'
testGroupDict['DIRECT LDL'] = 'LDL'
testGroupDict['ALT/SGPT'] = 'ALT'
testGroupDict['DIRECT BILIRUBIN'] = 'DirectBilirubin'
testGroupDict['AST/SGOT'] = 'AST'
testGroupDict['VITAMIN D, 25-OH D2'] = 'VitaminD_25'
testGroupDict['VITAMIN D, 25-OH D3'] = 'VitaminD_25'
testGroupDict['VITAMIN D, 25-OH TOT'] = 'VitaminD_25'
testGroupDict['FASTING GLUCOSE'] = 'Glucose'
testGroupDict['TOTAL CK'] = 'CK'
testGroupDict['TIBC'] = 'TIBC'
testGroupDict['TRIGLYCERIDES'] = 'Triglycerides'


testGroupDict['ICD9_Diagnosis'] = 'ICD9_Diagnosis'
testGroupDict['ICD9_Hospitalization'] = 'ICD9_Hospitalization'
testGroupDict['Lung_Cancer'] = 'Lung_Cancer' # Added Manually
testGroupDict['site_desc'] = 'Lung_Cancer_Location'
testGroupDict['TUMOR_SIZE'] = 'Lung_Cancer_Size'
testGroupDict['stage'] = 'Lung_Cancer_Stage'
testGroupDict['t_value'] = 'Lung_Cancer_T_Value'
testGroupDict['n_value'] = 'Lung_Cancer_N_Value'
testGroupDict['m_value'] = 'Lung_Cancer_M_Value'
testGroupDict['histology'] = 'Lung_Cancer_Type'
testGroupDict['SEQUENCE_NUMBER'] = 'Lung_Sequence_Number'

testGroupDict['BMI'] = 'BMI'
testGroupDict['TOBACCO_USER'] = 'Smoking_Status'
testGroupDict['smoking_quit_date'] = 'Smoking_Quit_Date'
testGroupDict['pkyr'] = 'Pack_Years'
testGroupDict['ALCOHOL_USER'] = 'Alcohol_Status'
testGroupDict['FEV1_PERCENT_PREDICTED'] = 'Fev1'
testGroupDict['FEV1_FVC'] = 'Fev1/Fvc'


#testGroupDict['NA'] = 'ICD9_Diagnosis'
#testGroupDict['NA'] 

# 'IRON SAT' 1 Occur
# 'SERUM SPECIMEN' 1 Occur 
#ttt = dfControlLab['component2']
#tt = ttt.value_counts()
#tt['APTT']
testGroupRevDict = dict()
# Create oppsoite dict
for k,v in testGroupDict.items():
    if v in testGroupRevDict:
        testGroupRevDict[v].append(k)
    else:
        testGroupRevDict[v] = [k]