name: Build medpython-etl PyPi

on:
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Publish to PyPI?'
        required: true
        default: false
        type: boolean

jobs:
  build_py_package:
    name: Build on Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Python
        run: |
          python -m pip install build
      # --- BUILD PYTHON PACKAGE ---
      - name: Build Python Packages
        run: |
          mkdir -p build/src/ETL_Infra
          cp -R RepoLoadUtils/common/ETL_Infra/*.py build/src/ETL_Infra
          cp -R RepoLoadUtils/common/ETL_Infra/tests build/src/ETL_Infra
          cp -R RepoLoadUtils/common/ETL_Infra/rep_signals build/src/ETL_Infra
          cp -R RepoLoadUtils/common/ETL_Infra/data_fetcher build/src/ETL_Infra
          cp -R RepoLoadUtils/common/ETL_Infra/dicts build/src/ETL_Infra
          cp RepoLoadUtils/common/MANIFEST.in RepoLoadUtils/common/pyproject.toml RepoLoadUtils/common/README.md RepoLoadUtils/common/LICENCE build
          cd build
          python -m build . --outdir dist
          
      # --- UPLOAD ARTIFACT (Prepare for Job 2) ---
      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: py-wheels
          # We grab the repaired wheels from wheelhouse
          path: build/dist/*
          retention-days: 1
      # - name: Test MedPython
      #   run: |
      #     python -c 'import med'


# --- JOB 2: PUBLISH (Runs on Linux) ---
  publish_to_pypi:
    name: Publish to PyPI
    needs: build_py_package
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_to_pypi == true }}
    environment:
      name: pypi
      url: https://pypi.org/project/medpython-etl

    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Download Wheels
        uses: actions/download-artifact@v4
        with:
          name: py-wheels
          path: dist/  # Put them in a 'dist' folder for the publisher

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
